# Generated by Django 6.0.6 on 2026-07-04 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_real_access_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=180)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=40)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='api.city')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
