# Generated by Django 6.0.6 on 2026-07-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_supplier_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('input_unit', models.CharField(choices=[('liters', 'Литры'), ('kilograms', 'Килограммы')], default='liters', max_length=12)),
                ('quantity_liters', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_receipts', to='api.supplier')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.DecimalField(decimal_places=4, max_digits=8)),
                ('flash_point_temperature', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_temperature', models.DecimalField(decimal_places=2, max_digits=8)),
                ('water_percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_analysis', to='api.rawmaterialreceipt')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
