# Generated by Django 6.0.6 on 2026-07-05 14:55

from django.db import migrations, models


def create_missing_laboratory_analyses(apps, schema_editor):
    RawMaterialReceipt = apps.get_model('api', 'RawMaterialReceipt')
    LaboratoryAnalysis = apps.get_model('api', 'LaboratoryAnalysis')

    existing_receipt_ids = LaboratoryAnalysis.objects.values_list('receipt_id', flat=True)
    missing_receipts = RawMaterialReceipt.objects.exclude(pk__in=existing_receipt_ids)
    LaboratoryAnalysis.objects.bulk_create([
        LaboratoryAnalysis(receipt=receipt)
        for receipt in missing_receipts
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_update_laboratory_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryanalysis',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laboratoryanalysis',
            name='current_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoryanalysis',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoryanalysis',
            name='flash_point_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoryanalysis',
            name='water_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialreceipt',
            name='input_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.RunPython(create_missing_laboratory_analyses, migrations.RunPython.noop),
    ]
