# Generated by Django 6.0.6 on 2026-07-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_laboratoryanalysis_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryanalysis',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
