# Generated by Django 6.0.6 on 2026-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_create_operational_access_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialreceipt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
