# Generated by Django 6.0.6 on 2026-07-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_receipt_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryanalysis',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialreceipt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
